name: sshtoserver

on: 
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy-to-server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}

