name: sshtoserver

on: 
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy-to-server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.ec2_HOST }}
                username: ${{ secrets.USERNAME }}
                Key: ${{ secrets.PRIVATE_KEY }}
                script: |
                   echo "Deploying to server..."
                   mkdir -p devops
                

