# name of the workflow
name: Hello


on:
  push:
    branches: [main]


jobs:

# name of the job
 greet:

 # 
  runs-on: ubuntu-latest
  steps:
     - name : say hello
       run: echo "hello mayuri"

     - name:  say hello username
       run: echo "$user"

 versionpython:
   runs-on: ubuntu-latest
   steps:
     - name: knwo the python vserion
       run: python --version
