#api secrets api key secret key
name: secrets scan

on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # fetch all history for gitleaks to work properly    

            - name: run gitleaks secret scan
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for gitleaks to comment on pull requests github_token is automatically provided by github actions, no need to set it up in the repository secrets 
            